[ue]
phy = nr

[rf]
device_name = bladeRF
srate = 11.52e6
nof_antennas = 1
freq_offset = 6000
rx_gain = 40
tx_gain = 60
continuous_tx = no
time_adv_nsamples = 300

[rat.eutra]
nof_carriers = 0

[rat.nr]
bands = 3
nof_carriers = 1
max_nof_prb = 52
dl_nr_arfcn = 368500
ssb_nr_arfcn = 367930
nof_prb = 52
scs = 15
ssb_scs = 15

[pcap]
mac_nr_filename = /tmp/ue_mac_nr_ota.pcap
nas_filename = /tmp/ue_nas_ota.pcap

[log]
phy_lib_level = warning
all_level = info
filename = /tmp/ue_ota.log
file_max_size = -1

[usim]
mode = soft
algo = milenage
opc = <SECRET_OPC>
k = <SECRET_K>
imsi = <SECRET_IMSI>
imei = <PRIVATE_IMEI>

[nas]
apn = internet
apn_protocol = ipv4
force_imsi_attach = true

[gw]
ip_devname = tun_ue_ota
ip_netmask = 255.255.255.0

[gui]
enable = false
