[ue]
phy = nr

[rf]
device_name = zmq
device_args = tx_port=tcp://127.0.0.1:2001,rx_port=tcp://127.0.0.1:2000,base_srate=23040000,id=ue
srate = 23.04e6
nof_antennas = 1
continuous_tx = yes

[rat.eutra]
nof_carriers = 0
dl_earfcn = 3350

[rat.nr]
bands = 78
nof_carriers = 1
max_nof_prb = 51
dl_nr_arfcn = 626000
ssb_nr_arfcn = 625632
nof_prb = 51
scs = 30
ssb_scs = 30

[pcap]
mac_nr_filename = /tmp/ue_mac_nr_zmq.pcap
nas_filename = /tmp/ue_nas_zmq.pcap

[log]
phy_lib_level = warning
all_level = info
filename = /tmp/ue_dbg.log
file_max_size = -1

[usim]
mode = soft
algo = milenage
opc = <SECRET_OPC>
k = <SECRET_K>
imsi = <SECRET_IMSI>
imei = <PRIVATE_IMEI>

[nas]
apn = internet
apn_protocol = ipv4
force_imsi_attach = true

[gw]
netns = ue1
ip_devname = tun_ue1
ip_netmask = 255.255.255.0

[gui]
enable = false
