//--------------------------------------------------------------------------------
// Auto-generated by LiteX (e2625f98d) on 2026-05-29 13:15:49
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef CSR_BASE
#define CSR_BASE 0x00000000L
#define CSR_SIZE 0x00020000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "CSR  0x00000000 0x20000 "
#endif
#endif
