#!/usr/bin/env bash
set -euo pipefail

REAL_GNB="${PAVONIS_CP3594_REAL_GNB:-@REMOTE_HOME@/pavonis_cp3109_scheduler_conres_rebase_gnb/gnb}"
REAL_GNB_SHA="${PAVONIS_CP3594_REAL_GNB_SHA:-90a5db019d52b3f893572d96a8338eae67a81b1e4169e8eb12c4afab20375f8a}"
OVERLAY="${PAVONIS_CP3594_OVERLAY:-@REMOTE_HOME@/cp3584_phone_15mhz_1x1_overlay.yml}"
OVERLAY_SHA="${PAVONIS_CP3594_OVERLAY_SHA:-818f39f71cb398d92a59eff1b11be1c5593b76f6a0ddfa16cc551fe3eed5808f}"

[[ "$(sha256sum "$REAL_GNB" | awk '{print $1}')" == "$REAL_GNB_SHA" ]]
[[ "$(sha256sum "$OVERLAY" | awk '{print $1}')" == "$OVERLAY_SHA" ]]
[[ "$(grep -c '^  srate: 15.36$' "$OVERLAY")" == 1 ]]
[[ "$(grep -c '^  channel_bandwidth_MHz: 15$' "$OVERLAY")" == 1 ]]

if [[ "${PAVONIS_CP3594_GNB_WRAPPER_PROBE:-0}" == 1 ]]; then
  cat <<'EOF'
CP3594_REAL_GNB_SHA=90a5db019d52b3f893572d96a8338eae67a81b1e4169e8eb12c4afab20375f8a
CP3594_SAMPLE_RATE_MSPS=15.36
CP3594_CHANNEL_BANDWIDTH_MHZ=15
CP3594_NOF_ANTENNAS_UL=1
CP3594_NOF_ANTENNAS_DL=1
CP3594_PHYSICAL_CHANNEL_OFFSET=0
CP3594_CONTEXT_EDGE_TRANSPORT=1
CP3594_COMMIT_ON_UPPER_ACCEPT=1
CP3594_EDGE_CALIBRATION_SAMPLES=-316443
CP3594_EDGE_HOST_ACTIVE_STOP_SAMPLES=13872
CP3594_EDGE_LATTICE_PERIOD_SAMPLES=1097
CP3594_EDGE_LATTICE_ANCHOR_SAMPLES=-184
CP3594_EDGE_LATTICE_CANONICAL_SAMPLES=-8960
CP3594_EDGE_LATTICE_INDEX=-8
CP3594_NON_PRACH_UL_RX_CFO_HZ=0
CP3594_FALLBACK_DL_DCI_AGGR_LEV=8
CP3594_GNB_WRAPPER_PROBE=PASS
EOF
  exit 0
fi

export PAVONIS_NON_PRACH_UL_RX_OFFSET_COMMIT_ON_UPPER_ACCEPT=1
export PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_CALIBRATION_SAMPLES=-316443
export PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_HOST_ACTIVE_STOP_SAMPLES=13872
export PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_LATTICE_PERIOD_SAMPLES=1097
export PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_LATTICE_ANCHOR_SAMPLES=-184
export PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_LATTICE_CANONICAL_SAMPLES=-8960
export PAVONIS_NON_PRACH_UL_RX_CFO_HZ=0
export PAVONIS_NON_PRACH_UL_RX_OFFSET_TRACE_LIMIT=256
export PAVONIS_SOAPY_PHYSICAL_CHANNEL_OFFSET=0
export PAVONIS_PUSCH_CSI_TRACE=1
export PAVONIS_PUSCH_CSI_TRACE_LIMIT=256
export PAVONIS_PUSCH_EVM_DIAGNOSTIC=1
export PAVONIS_PUXCH_ORDER_TRACE=1
export PAVONIS_PUXCH_ORDER_TRACE_LIMIT=500
export PAVONIS_PUXCH_ORDER_TRACE_LATE_ARM=1
export PAVONIS_MSG3_PATH_TRACE=1
export PAVONIS_MSG3_PATH_TRACE_LIMIT=1024
export PAVONIS_GNB_FALLBACK_DL_DCI_AGGR_LEV=8

unset PAVONIS_MSG3_CONRES_SLOT_REBASE_FROM_NON_PRACH
unset PAVONIS_MSG3_CONRES_SAMPLES_PER_SLOT
unset PAVONIS_MSG3_CONRES_MAX_SLOT_OFFSET
unset PAVONIS_MSG3_CONRES_SLOT_REBASE_TRACE_LIMIT

if [[ "${PAVONIS_CP3594_GNB_WRAPPER_ENV_PROBE:-0}" == 1 ]]; then
  [[ "$PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_CALIBRATION_SAMPLES" == -316443 ]]
  [[ "$PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_HOST_ACTIVE_STOP_SAMPLES" == 13872 ]]
  [[ "$PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_LATTICE_PERIOD_SAMPLES" == 1097 ]]
  [[ "$PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_LATTICE_ANCHOR_SAMPLES" == -184 ]]
  [[ "$PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_LATTICE_CANONICAL_SAMPLES" == -8960 ]]
  [[ "$PAVONIS_SOAPY_PHYSICAL_CHANNEL_OFFSET" == 0 ]]
  ((PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_LATTICE_CANONICAL_SAMPLES -
    PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_LATTICE_ANCHOR_SAMPLES ==
    -8 * PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_LATTICE_PERIOD_SAMPLES))
  [[ "$PAVONIS_GNB_FALLBACK_DL_DCI_AGGR_LEV" == 8 ]]
  [[ "${PAVONIS_MSG3_CONRES_SLOT_REBASE_FROM_NON_PRACH+set}" != set ]]
  printf 'CP3594_EFFECTIVE_EDGE_CALIBRATION_SAMPLES=%s\n' \
    "$PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_CALIBRATION_SAMPLES"
  printf 'CP3594_EFFECTIVE_EDGE_HOST_ACTIVE_STOP_SAMPLES=%s\n' \
    "$PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_HOST_ACTIVE_STOP_SAMPLES"
  printf 'CP3594_EFFECTIVE_EDGE_LATTICE_PERIOD_SAMPLES=%s\n' \
    "$PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_LATTICE_PERIOD_SAMPLES"
  printf 'CP3594_EFFECTIVE_EDGE_LATTICE_ANCHOR_SAMPLES=%s\n' \
    "$PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_LATTICE_ANCHOR_SAMPLES"
  printf 'CP3594_EFFECTIVE_EDGE_LATTICE_CANONICAL_SAMPLES=%s\n' \
    "$PAVONIS_NON_PRACH_UL_RX_OFFSET_EDGE_LATTICE_CANONICAL_SAMPLES"
  printf 'CP3594_EFFECTIVE_EDGE_LATTICE_INDEX=-8\n'
  printf 'CP3594_EFFECTIVE_PHYSICAL_CHANNEL_OFFSET=%s\n' \
    "$PAVONIS_SOAPY_PHYSICAL_CHANNEL_OFFSET"
  printf 'CP3594_GNB_WRAPPER_ENV_PROBE=PASS\n'
  exit 0
fi

printf 'PAVONIS_CP3594_PHONE_15MHZ_1X1_MAP0_GNB_WRAPPER_ACTIVE overlay_sha=%s physical_channel_offset=0 edge_calibration=-316443 active_stop=13872 edge_lattice=1097,-184,-8960,index=-8\n' \
  "$OVERLAY_SHA"
exec "$REAL_GNB" "$@" -c "$OVERLAY"
