#!/usr/bin/env bash
set -euo pipefail

TAG="${TAG:-codex_stage6_cp193_high_peak_tx_now}"
STAMP="${STAMP:-$(date -u +%Y%m%dT%H%M%SZ)}"
BASE="${SENS_BASE:-$HOME/pavonis_bladerf/ota_attach_best_${TAG}_${STAMP}}"
SRC_CONF="${SRC_CONF:-$HOME/pavonis_bladerf/ota_attach_best_20260626T114555Z/run_20260626T114555Z/ue-bladerf-band3-ota.best.conf}"

export BASE
export SRC_CONF
"$HOME/CLionProjects/pavonis_toolkit/scripts/pavonis_prepare_srsue_best_config_ue.sh"

OUT="$(ls -td "$BASE"/run_* | head -1)"
ENVF="$OUT/prepared.env"
test -f "$ENVF"
. "$ENVF"

if [ -n "${UE_TX_GAIN_DB:-}" ]; then
  test -f "$CONF"
  cp "$CONF" "$CONF.before_ue_tx_gain_override"
  tmp_conf="$CONF.ue_tx_gain_override.tmp"
  sed -E "s/^([[:space:]]*tx_gain[[:space:]]*=[[:space:]]*).*/\1${UE_TX_GAIN_DB}/" "$CONF" > "$tmp_conf"
  mv "$tmp_conf" "$CONF"
  echo "UE_TX_GAIN_DB_OVERRIDE=$UE_TX_GAIN_DB"
  echo "CONF_TX_GAIN_LINE=$(grep -n 'tx_gain[[:space:]]*=' "$CONF" | head -1)"
fi

TIMEOUT_SEC="${TIMEOUT_SEC:-240}"
KILL_AFTER_SEC="${KILL_AFTER_SEC:-8}"
PAVONIS_RF_BLADE_TX_DBG_DUMP_COUNT="${PAVONIS_RF_BLADE_TX_DBG_DUMP_COUNT:-8}"
if [ "${PAVONIS_PUSCH_CSI_TRACE:-0}" = "1" ] &&
   [ "${PAVONIS_UL_SYMBOL_MSG3_TARGET_CAPTURE:-0}" = "1" ] &&
   [[ "$PAVONIS_RF_BLADE_TX_DBG_DUMP_COUNT" =~ ^[0-9]+$ ]] &&
   [ "$PAVONIS_RF_BLADE_TX_DBG_DUMP_COUNT" -lt 16 ]; then
  PAVONIS_RF_BLADE_TX_DBG_DUMP_COUNT=16
fi
RUNNER="$OUT/run_srsue_bounded.sh"

cat > "$RUNNER" <<'RUNNER_EOF'
#!/usr/bin/env bash
set +e +u
set +o pipefail 2>/dev/null || true
START_UTC="$(date -u --iso-8601=ns)"
timeout --kill-after="${KILL_AFTER_SEC}s" "$TIMEOUT_SEC" sudo -n env \
	  PAVONIS_SRSUE_CELL_SELECT_TRACE="${PAVONIS_SRSUE_CELL_SELECT_TRACE:-0}" \
	  PAVONIS_SRSUE_SIB1_TRACE="${PAVONIS_SRSUE_SIB1_TRACE:-0}" \
	  PAVONIS_SRSUE_SIB1_TRACE_LIMIT="${PAVONIS_SRSUE_SIB1_TRACE_LIMIT:-400}" \
	  PAVONIS_SRSUE_SIB1_TRACE_PDCCH_SUMMARY_INTERVAL="${PAVONIS_SRSUE_SIB1_TRACE_PDCCH_SUMMARY_INTERVAL:-200}" \
	  PAVONIS_SRSUE_SI_CANDIDATE_TRACE="${PAVONIS_SRSUE_SI_CANDIDATE_TRACE:-0}" \
	  PAVONIS_SRSUE_SI_CANDIDATE_TRACE_LIMIT="${PAVONIS_SRSUE_SI_CANDIDATE_TRACE_LIMIT:-200}" \
	  PAVONIS_SRSUE_SI_CANDIDATE_TRACE_MIN_CORR="${PAVONIS_SRSUE_SI_CANDIDATE_TRACE_MIN_CORR:-0.40}" \
	  PAVONIS_SRSUE_SI_CFO_PROVENANCE_TRACE="${PAVONIS_SRSUE_SI_CFO_PROVENANCE_TRACE:-0}" \
	  PAVONIS_SRSUE_PRACH_CFG_DBG="${PAVONIS_SRSUE_PRACH_CFG_DBG:-1}" \
  PAVONIS_SRSUE_RAR_TRACE="${PAVONIS_SRSUE_RAR_TRACE:-0}" \
  PAVONIS_SRSUE_RAR_TRACE_LIMIT="${PAVONIS_SRSUE_RAR_TRACE_LIMIT:-240}" \
  PAVONIS_SRSUE_RAR_CANDIDATE_TRACE="${PAVONIS_SRSUE_RAR_CANDIDATE_TRACE:-0}" \
  PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_LIMIT="${PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_LIMIT:-200}" \
  PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_MIN_CORR="${PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_MIN_CORR:-0.20}" \
  PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE="${PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE:-0}" \
  PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_LIMIT="${PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_LIMIT:-256}" \
  PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_MIN_CORR="${PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_MIN_CORR:-0.20}" \
  PAVONIS_SRSUE_TA_HANDOFF_TRACE="${PAVONIS_SRSUE_TA_HANDOFF_TRACE:-0}" \
  PAVONIS_SRSUE_TA_HANDOFF_APPLY_CURRENT="${PAVONIS_SRSUE_TA_HANDOFF_APPLY_CURRENT:-0}" \
  PAVONIS_SRSUE_TA_HANDOFF_TRACE_LIMIT="${PAVONIS_SRSUE_TA_HANDOFF_TRACE_LIMIT:-64}" \
  PAVONIS_SRSUE_TA_OFFSET_PRESERVE_COMMAND="${PAVONIS_SRSUE_TA_OFFSET_PRESERVE_COMMAND:-0}" \
  PAVONIS_SRSUE_RAR_TRACE_LATE_ARM="${PAVONIS_SRSUE_RAR_TRACE_LATE_ARM:-1}" \
  PAVONIS_SRSUE_RAR_WINDOW_TRACE="${PAVONIS_SRSUE_RAR_WINDOW_TRACE:-0}" \
  SRSUE_PRACH_TX_DBG="${SRSUE_PRACH_TX_DBG:-1}" \
  PAVONIS_RF_BLADE_TX_DBG="${PAVONIS_RF_BLADE_TX_DBG:-1}" \
  PAVONIS_RF_BLADE_TX_DBG_FIRST="${PAVONIS_RF_BLADE_TX_DBG_FIRST:-16}" \
  PAVONIS_RF_BLADE_TX_DBG_MAX_LINES="${PAVONIS_RF_BLADE_TX_DBG_MAX_LINES:-260}" \
  PAVONIS_RF_BLADE_TX_DBG_MIN_PEAK="${PAVONIS_RF_BLADE_TX_DBG_MIN_PEAK:-0.20}" \
  PAVONIS_RF_BLADE_TX_DBG_DUMP_COUNT="${PAVONIS_RF_BLADE_TX_DBG_DUMP_COUNT:-8}" \
  PAVONIS_RF_BLADE_TX_DBG_DUMP_DIR="${PAVONIS_RF_BLADE_TX_DBG_DUMP_DIR:-$OUT}" \
  PAVONIS_RF_BLADE_TX_DBG_PRE_TX="${PAVONIS_RF_BLADE_TX_DBG_PRE_TX:-1}" \
  PAVONIS_RF_BLADE_TX_DBG_PRE_TX_ALL="${PAVONIS_RF_BLADE_TX_DBG_PRE_TX_ALL:-0}" \
  PAVONIS_RF_BLADE_TX_DBG_TX_GUARD_SAMPLES="${PAVONIS_RF_BLADE_TX_DBG_TX_GUARD_SAMPLES:-30000}" \
  PAVONIS_RF_BLADE_TX_DBG_PRACH_TIME_OFFSET_SAMPLES="${PAVONIS_RF_BLADE_TX_DBG_PRACH_TIME_OFFSET_SAMPLES:-0}" \
  PAVONIS_RF_BLADE_TX_DBG_PRACH_FREQ_ROT_HZ="${PAVONIS_RF_BLADE_TX_DBG_PRACH_FREQ_ROT_HZ:-0}" \
  PAVONIS_RF_BLADE_TX_DBG_HIGH_PEAK_TX_NOW="${PAVONIS_RF_BLADE_TX_DBG_HIGH_PEAK_TX_NOW:-0}" \
  PAVONIS_RF_BLADE_TX_DBG_COHERENT_GUARD_BIAS="${PAVONIS_RF_BLADE_TX_DBG_COHERENT_GUARD_BIAS:-0}" \
  PAVONIS_RF_BLADE_TX_DBG_RESTART_TX_STREAM_ON_FIRST_HIGH_PEAK="${PAVONIS_RF_BLADE_TX_DBG_RESTART_TX_STREAM_ON_FIRST_HIGH_PEAK:-0}" \
  PAVONIS_RF_BLADE_TX_DBG_DISABLE_SOB_AFTER_ERROR="${PAVONIS_RF_BLADE_TX_DBG_DISABLE_SOB_AFTER_ERROR:-0}" \
  PAVONIS_RF_BLADE_TX_DBG_SKIP_AFTER_ERROR="${PAVONIS_RF_BLADE_TX_DBG_SKIP_AFTER_ERROR:-0}" \
  PAVONIS_SRSUE_PRACH_SYNC_GUARD_SLOTS="${PAVONIS_SRSUE_PRACH_SYNC_GUARD_SLOTS:-0}" \
  PAVONIS_SRSUE_PRACH_SYNC_GUARD_TRACE="${PAVONIS_SRSUE_PRACH_SYNC_GUARD_TRACE:-0}" \
  PAVONIS_SRSUE_PRACH_DEFER_MS="${PAVONIS_SRSUE_PRACH_DEFER_MS:-0}" \
  PAVONIS_SRSUE_CAMPING_TTI_TRACE="${PAVONIS_SRSUE_CAMPING_TTI_TRACE:-0}" \
  PAVONIS_SRSUE_CAMPING_TTI_ALIGN="${PAVONIS_SRSUE_CAMPING_TTI_ALIGN:-0}" \
  PAVONIS_SRSUE_UL_TX_LATTICE="${PAVONIS_SRSUE_UL_TX_LATTICE:-0}" \
  PAVONIS_SRSUE_UL_TX_LATTICE_MAX_SLEW_SAMPLES="${PAVONIS_SRSUE_UL_TX_LATTICE_MAX_SLEW_SAMPLES:-1}" \
  PAVONIS_SRSUE_SFN_ACQ_HANDOFF="${PAVONIS_SRSUE_SFN_ACQ_HANDOFF:-0}" \
  PAVONIS_SRSUE_SFN_ACQ_TARGET_OFFSET_SAMPLES="${PAVONIS_SRSUE_SFN_ACQ_TARGET_OFFSET_SAMPLES:-2048}" \
  PAVONIS_SRSUE_SR_PUCCH_TRACE="${PAVONIS_SRSUE_SR_PUCCH_TRACE:-0}" \
  PAVONIS_SRSUE_SR_PUCCH_TRACE_LIMIT="${PAVONIS_SRSUE_SR_PUCCH_TRACE_LIMIT:-256}" \
  PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_SOB="${PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_SOB:-0}" \
  PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_EOB="${PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_EOB:-0}" \
  PAVONIS_RF_BLADE_HIGH_PEAK_EOB_THEN_SOB="${PAVONIS_RF_BLADE_HIGH_PEAK_EOB_THEN_SOB:-0}" \
  PAVONIS_RF_BLADE_PRACH_BURST_ONLY="${PAVONIS_RF_BLADE_PRACH_BURST_ONLY:-0}" \
  PAVONIS_RF_BLADE_STATE_DBG="${PAVONIS_RF_BLADE_STATE_DBG:-1}" \
  PAVONIS_RF_BLADE_STATE_DBG_MAX_LINES="${PAVONIS_RF_BLADE_STATE_DBG_MAX_LINES:-500}" \
  PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_FIRST="${PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_FIRST:-40}" \
  PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_EVERY="${PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_EVERY:-256}" \
  SRSRAN_RF_PLUGIN_DIR="$RF_PLUGIN_DIR" \
  LD_LIBRARY_PATH="$RF_PLUGIN_DIR:${LD_LIBRARY_PATH:-}" \
  "$SRSUE_BIN" "$CONF" > "$UE_STDOUT" 2>&1
RC=$?
END_UTC="$(date -u --iso-8601=ns)"
cat > "$OUT/result.env" <<EOF2
START_UTC=$START_UTC
END_UTC=$END_UTC
RC=$RC
OUT=$OUT
CONF=$CONF
UE_STDOUT=$UE_STDOUT
UE_DETAIL=$UE_DETAIL
	PAVONIS_SRSUE_CELL_SELECT_TRACE=${PAVONIS_SRSUE_CELL_SELECT_TRACE:-0}
	PAVONIS_SRSUE_SIB1_TRACE=${PAVONIS_SRSUE_SIB1_TRACE:-0}
	PAVONIS_SRSUE_SIB1_TRACE_LIMIT=${PAVONIS_SRSUE_SIB1_TRACE_LIMIT:-400}
	PAVONIS_SRSUE_SIB1_TRACE_PDCCH_SUMMARY_INTERVAL=${PAVONIS_SRSUE_SIB1_TRACE_PDCCH_SUMMARY_INTERVAL:-200}
	PAVONIS_SRSUE_SI_CANDIDATE_TRACE=${PAVONIS_SRSUE_SI_CANDIDATE_TRACE:-0}
	PAVONIS_SRSUE_SI_CANDIDATE_TRACE_LIMIT=${PAVONIS_SRSUE_SI_CANDIDATE_TRACE_LIMIT:-200}
	PAVONIS_SRSUE_SI_CANDIDATE_TRACE_MIN_CORR=${PAVONIS_SRSUE_SI_CANDIDATE_TRACE_MIN_CORR:-0.40}
	PAVONIS_SRSUE_SI_CFO_PROVENANCE_TRACE=${PAVONIS_SRSUE_SI_CFO_PROVENANCE_TRACE:-0}
	PAVONIS_SRSUE_PRACH_CFG_DBG=${PAVONIS_SRSUE_PRACH_CFG_DBG:-1}
PAVONIS_SRSUE_RAR_TRACE=${PAVONIS_SRSUE_RAR_TRACE:-0}
PAVONIS_SRSUE_RAR_TRACE_LIMIT=${PAVONIS_SRSUE_RAR_TRACE_LIMIT:-240}
PAVONIS_SRSUE_RAR_CANDIDATE_TRACE=${PAVONIS_SRSUE_RAR_CANDIDATE_TRACE:-0}
PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_LIMIT=${PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_LIMIT:-200}
PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_MIN_CORR=${PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_MIN_CORR:-0.20}
PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE=${PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE:-0}
PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_LIMIT=${PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_LIMIT:-256}
PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_MIN_CORR=${PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_MIN_CORR:-0.20}
PAVONIS_SRSUE_TA_HANDOFF_TRACE=${PAVONIS_SRSUE_TA_HANDOFF_TRACE:-0}
PAVONIS_SRSUE_TA_HANDOFF_APPLY_CURRENT=${PAVONIS_SRSUE_TA_HANDOFF_APPLY_CURRENT:-0}
PAVONIS_SRSUE_TA_HANDOFF_TRACE_LIMIT=${PAVONIS_SRSUE_TA_HANDOFF_TRACE_LIMIT:-64}
PAVONIS_SRSUE_TA_OFFSET_PRESERVE_COMMAND=${PAVONIS_SRSUE_TA_OFFSET_PRESERVE_COMMAND:-0}
PAVONIS_SRSUE_RAR_TRACE_LATE_ARM=${PAVONIS_SRSUE_RAR_TRACE_LATE_ARM:-1}
PAVONIS_SRSUE_RAR_WINDOW_TRACE=${PAVONIS_SRSUE_RAR_WINDOW_TRACE:-0}
SRSUE_PRACH_TX_DBG=${SRSUE_PRACH_TX_DBG:-1}
PAVONIS_RF_BLADE_TX_DBG=${PAVONIS_RF_BLADE_TX_DBG:-1}
PAVONIS_RF_BLADE_TX_DBG_FIRST=${PAVONIS_RF_BLADE_TX_DBG_FIRST:-16}
PAVONIS_RF_BLADE_TX_DBG_MAX_LINES=${PAVONIS_RF_BLADE_TX_DBG_MAX_LINES:-260}
PAVONIS_RF_BLADE_TX_DBG_MIN_PEAK=${PAVONIS_RF_BLADE_TX_DBG_MIN_PEAK:-0.20}
PAVONIS_RF_BLADE_TX_DBG_DUMP_COUNT=${PAVONIS_RF_BLADE_TX_DBG_DUMP_COUNT:-8}
PAVONIS_RF_BLADE_TX_DBG_DUMP_DIR=${PAVONIS_RF_BLADE_TX_DBG_DUMP_DIR:-$OUT}
PAVONIS_RF_BLADE_TX_DBG_PRE_TX=${PAVONIS_RF_BLADE_TX_DBG_PRE_TX:-1}
PAVONIS_RF_BLADE_TX_DBG_PRE_TX_ALL=${PAVONIS_RF_BLADE_TX_DBG_PRE_TX_ALL:-0}
PAVONIS_RF_BLADE_TX_DBG_TX_GUARD_SAMPLES=${PAVONIS_RF_BLADE_TX_DBG_TX_GUARD_SAMPLES:-30000}
PAVONIS_RF_BLADE_TX_DBG_PRACH_TIME_OFFSET_SAMPLES=${PAVONIS_RF_BLADE_TX_DBG_PRACH_TIME_OFFSET_SAMPLES:-0}
PAVONIS_RF_BLADE_TX_DBG_PRACH_FREQ_ROT_HZ=${PAVONIS_RF_BLADE_TX_DBG_PRACH_FREQ_ROT_HZ:-0}
PAVONIS_RF_BLADE_TX_DBG_HIGH_PEAK_TX_NOW=${PAVONIS_RF_BLADE_TX_DBG_HIGH_PEAK_TX_NOW:-0}
PAVONIS_RF_BLADE_TX_DBG_COHERENT_GUARD_BIAS=${PAVONIS_RF_BLADE_TX_DBG_COHERENT_GUARD_BIAS:-0}
PAVONIS_RF_BLADE_TX_DBG_RESTART_TX_STREAM_ON_FIRST_HIGH_PEAK=${PAVONIS_RF_BLADE_TX_DBG_RESTART_TX_STREAM_ON_FIRST_HIGH_PEAK:-0}
PAVONIS_RF_BLADE_TX_DBG_DISABLE_SOB_AFTER_ERROR=${PAVONIS_RF_BLADE_TX_DBG_DISABLE_SOB_AFTER_ERROR:-0}
PAVONIS_RF_BLADE_TX_DBG_SKIP_AFTER_ERROR=${PAVONIS_RF_BLADE_TX_DBG_SKIP_AFTER_ERROR:-0}
PAVONIS_SRSUE_PRACH_SYNC_GUARD_SLOTS=${PAVONIS_SRSUE_PRACH_SYNC_GUARD_SLOTS:-0}
PAVONIS_SRSUE_PRACH_SYNC_GUARD_TRACE=${PAVONIS_SRSUE_PRACH_SYNC_GUARD_TRACE:-0}
PAVONIS_SRSUE_PRACH_DEFER_MS=${PAVONIS_SRSUE_PRACH_DEFER_MS:-0}
PAVONIS_SRSUE_CAMPING_TTI_TRACE=${PAVONIS_SRSUE_CAMPING_TTI_TRACE:-0}
PAVONIS_SRSUE_CAMPING_TTI_ALIGN=${PAVONIS_SRSUE_CAMPING_TTI_ALIGN:-0}
PAVONIS_SRSUE_UL_TX_LATTICE=${PAVONIS_SRSUE_UL_TX_LATTICE:-0}
PAVONIS_SRSUE_UL_TX_LATTICE_MAX_SLEW_SAMPLES=${PAVONIS_SRSUE_UL_TX_LATTICE_MAX_SLEW_SAMPLES:-1}
PAVONIS_SRSUE_SFN_ACQ_HANDOFF=${PAVONIS_SRSUE_SFN_ACQ_HANDOFF:-0}
PAVONIS_SRSUE_SFN_ACQ_TARGET_OFFSET_SAMPLES=${PAVONIS_SRSUE_SFN_ACQ_TARGET_OFFSET_SAMPLES:-2048}
PAVONIS_SRSUE_SR_PUCCH_TRACE=${PAVONIS_SRSUE_SR_PUCCH_TRACE:-0}
PAVONIS_SRSUE_SR_PUCCH_TRACE_LIMIT=${PAVONIS_SRSUE_SR_PUCCH_TRACE_LIMIT:-256}
PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_SOB=${PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_SOB:-0}
PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_EOB=${PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_EOB:-0}
PAVONIS_RF_BLADE_HIGH_PEAK_EOB_THEN_SOB=${PAVONIS_RF_BLADE_HIGH_PEAK_EOB_THEN_SOB:-0}
PAVONIS_RF_BLADE_PRACH_BURST_ONLY=${PAVONIS_RF_BLADE_PRACH_BURST_ONLY:-0}
PAVONIS_RF_BLADE_STATE_DBG=${PAVONIS_RF_BLADE_STATE_DBG:-1}
PAVONIS_RF_BLADE_STATE_DBG_MAX_LINES=${PAVONIS_RF_BLADE_STATE_DBG_MAX_LINES:-500}
PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_FIRST=${PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_FIRST:-40}
PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_EVERY=${PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_EVERY:-256}
UE_TX_GAIN_DB_OVERRIDE=${UE_TX_GAIN_DB:-}
EOF2
sudo -n pkill -TERM -x srsue 2>/dev/null || true
sleep 2
sudo -n pkill -KILL -x srsue 2>/dev/null || true
exit 0
RUNNER_EOF

chmod +x "$RUNNER"
sudo -v
nohup env OUT="$OUT" CONF="$CONF" SRSUE_BIN="$SRSUE_BIN" RF_PLUGIN_DIR="$RF_PLUGIN_DIR" \
  UE_STDOUT="$UE_STDOUT" UE_DETAIL="$UE_DETAIL" TIMEOUT_SEC="$TIMEOUT_SEC" KILL_AFTER_SEC="$KILL_AFTER_SEC" \
	  PAVONIS_SRSUE_CELL_SELECT_TRACE="${PAVONIS_SRSUE_CELL_SELECT_TRACE:-0}" \
	  PAVONIS_SRSUE_SIB1_TRACE="${PAVONIS_SRSUE_SIB1_TRACE:-0}" \
	  PAVONIS_SRSUE_SIB1_TRACE_LIMIT="${PAVONIS_SRSUE_SIB1_TRACE_LIMIT:-400}" \
	  PAVONIS_SRSUE_SIB1_TRACE_PDCCH_SUMMARY_INTERVAL="${PAVONIS_SRSUE_SIB1_TRACE_PDCCH_SUMMARY_INTERVAL:-200}" \
	  PAVONIS_SRSUE_SI_CANDIDATE_TRACE="${PAVONIS_SRSUE_SI_CANDIDATE_TRACE:-0}" \
	  PAVONIS_SRSUE_SI_CANDIDATE_TRACE_LIMIT="${PAVONIS_SRSUE_SI_CANDIDATE_TRACE_LIMIT:-200}" \
	  PAVONIS_SRSUE_SI_CANDIDATE_TRACE_MIN_CORR="${PAVONIS_SRSUE_SI_CANDIDATE_TRACE_MIN_CORR:-0.40}" \
	  PAVONIS_SRSUE_SI_CFO_PROVENANCE_TRACE="${PAVONIS_SRSUE_SI_CFO_PROVENANCE_TRACE:-0}" \
	  PAVONIS_SRSUE_PRACH_CFG_DBG="${PAVONIS_SRSUE_PRACH_CFG_DBG:-1}" \
  PAVONIS_SRSUE_RAR_TRACE="${PAVONIS_SRSUE_RAR_TRACE:-0}" \
  PAVONIS_SRSUE_RAR_TRACE_LIMIT="${PAVONIS_SRSUE_RAR_TRACE_LIMIT:-240}" \
  PAVONIS_SRSUE_RAR_CANDIDATE_TRACE="${PAVONIS_SRSUE_RAR_CANDIDATE_TRACE:-0}" \
  PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_LIMIT="${PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_LIMIT:-200}" \
  PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_MIN_CORR="${PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_MIN_CORR:-0.20}" \
  PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE="${PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE:-0}" \
  PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_LIMIT="${PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_LIMIT:-256}" \
  PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_MIN_CORR="${PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_MIN_CORR:-0.20}" \
  PAVONIS_SRSUE_TA_HANDOFF_TRACE="${PAVONIS_SRSUE_TA_HANDOFF_TRACE:-0}" \
  PAVONIS_SRSUE_TA_HANDOFF_APPLY_CURRENT="${PAVONIS_SRSUE_TA_HANDOFF_APPLY_CURRENT:-0}" \
  PAVONIS_SRSUE_TA_HANDOFF_TRACE_LIMIT="${PAVONIS_SRSUE_TA_HANDOFF_TRACE_LIMIT:-64}" \
  PAVONIS_SRSUE_TA_OFFSET_PRESERVE_COMMAND="${PAVONIS_SRSUE_TA_OFFSET_PRESERVE_COMMAND:-0}" \
  PAVONIS_SRSUE_RAR_TRACE_LATE_ARM="${PAVONIS_SRSUE_RAR_TRACE_LATE_ARM:-1}" \
  PAVONIS_SRSUE_RAR_WINDOW_TRACE="${PAVONIS_SRSUE_RAR_WINDOW_TRACE:-0}" \
  SRSUE_PRACH_TX_DBG="${SRSUE_PRACH_TX_DBG:-1}" \
  PAVONIS_RF_BLADE_TX_DBG="${PAVONIS_RF_BLADE_TX_DBG:-1}" \
  PAVONIS_RF_BLADE_TX_DBG_FIRST="${PAVONIS_RF_BLADE_TX_DBG_FIRST:-16}" \
  PAVONIS_RF_BLADE_TX_DBG_MAX_LINES="${PAVONIS_RF_BLADE_TX_DBG_MAX_LINES:-260}" \
  PAVONIS_RF_BLADE_TX_DBG_MIN_PEAK="${PAVONIS_RF_BLADE_TX_DBG_MIN_PEAK:-0.20}" \
  PAVONIS_RF_BLADE_TX_DBG_DUMP_COUNT="${PAVONIS_RF_BLADE_TX_DBG_DUMP_COUNT:-8}" \
  PAVONIS_RF_BLADE_TX_DBG_DUMP_DIR="${PAVONIS_RF_BLADE_TX_DBG_DUMP_DIR:-$OUT}" \
  PAVONIS_RF_BLADE_TX_DBG_PRE_TX="${PAVONIS_RF_BLADE_TX_DBG_PRE_TX:-1}" \
  PAVONIS_RF_BLADE_TX_DBG_PRE_TX_ALL="${PAVONIS_RF_BLADE_TX_DBG_PRE_TX_ALL:-0}" \
  PAVONIS_RF_BLADE_TX_DBG_TX_GUARD_SAMPLES="${PAVONIS_RF_BLADE_TX_DBG_TX_GUARD_SAMPLES:-30000}" \
  PAVONIS_RF_BLADE_TX_DBG_PRACH_TIME_OFFSET_SAMPLES="${PAVONIS_RF_BLADE_TX_DBG_PRACH_TIME_OFFSET_SAMPLES:-0}" \
  PAVONIS_RF_BLADE_TX_DBG_PRACH_FREQ_ROT_HZ="${PAVONIS_RF_BLADE_TX_DBG_PRACH_FREQ_ROT_HZ:-0}" \
  PAVONIS_RF_BLADE_TX_DBG_HIGH_PEAK_TX_NOW="${PAVONIS_RF_BLADE_TX_DBG_HIGH_PEAK_TX_NOW:-0}" \
  PAVONIS_RF_BLADE_TX_DBG_COHERENT_GUARD_BIAS="${PAVONIS_RF_BLADE_TX_DBG_COHERENT_GUARD_BIAS:-0}" \
  PAVONIS_RF_BLADE_TX_DBG_RESTART_TX_STREAM_ON_FIRST_HIGH_PEAK="${PAVONIS_RF_BLADE_TX_DBG_RESTART_TX_STREAM_ON_FIRST_HIGH_PEAK:-0}" \
  PAVONIS_RF_BLADE_TX_DBG_DISABLE_SOB_AFTER_ERROR="${PAVONIS_RF_BLADE_TX_DBG_DISABLE_SOB_AFTER_ERROR:-0}" \
  PAVONIS_RF_BLADE_TX_DBG_SKIP_AFTER_ERROR="${PAVONIS_RF_BLADE_TX_DBG_SKIP_AFTER_ERROR:-0}" \
  PAVONIS_SRSUE_PRACH_SYNC_GUARD_SLOTS="${PAVONIS_SRSUE_PRACH_SYNC_GUARD_SLOTS:-0}" \
  PAVONIS_SRSUE_PRACH_SYNC_GUARD_TRACE="${PAVONIS_SRSUE_PRACH_SYNC_GUARD_TRACE:-0}" \
  PAVONIS_SRSUE_PRACH_DEFER_MS="${PAVONIS_SRSUE_PRACH_DEFER_MS:-0}" \
  PAVONIS_SRSUE_CAMPING_TTI_TRACE="${PAVONIS_SRSUE_CAMPING_TTI_TRACE:-0}" \
  PAVONIS_SRSUE_CAMPING_TTI_ALIGN="${PAVONIS_SRSUE_CAMPING_TTI_ALIGN:-0}" \
  PAVONIS_SRSUE_UL_TX_LATTICE="${PAVONIS_SRSUE_UL_TX_LATTICE:-0}" \
  PAVONIS_SRSUE_UL_TX_LATTICE_MAX_SLEW_SAMPLES="${PAVONIS_SRSUE_UL_TX_LATTICE_MAX_SLEW_SAMPLES:-1}" \
  PAVONIS_SRSUE_SFN_ACQ_HANDOFF="${PAVONIS_SRSUE_SFN_ACQ_HANDOFF:-0}" \
  PAVONIS_SRSUE_SFN_ACQ_TARGET_OFFSET_SAMPLES="${PAVONIS_SRSUE_SFN_ACQ_TARGET_OFFSET_SAMPLES:-2048}" \
  PAVONIS_SRSUE_SR_PUCCH_TRACE="${PAVONIS_SRSUE_SR_PUCCH_TRACE:-0}" \
  PAVONIS_SRSUE_SR_PUCCH_TRACE_LIMIT="${PAVONIS_SRSUE_SR_PUCCH_TRACE_LIMIT:-256}" \
  PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_SOB="${PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_SOB:-0}" \
  PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_EOB="${PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_EOB:-0}" \
  PAVONIS_RF_BLADE_HIGH_PEAK_EOB_THEN_SOB="${PAVONIS_RF_BLADE_HIGH_PEAK_EOB_THEN_SOB:-0}" \
  PAVONIS_RF_BLADE_PRACH_BURST_ONLY="${PAVONIS_RF_BLADE_PRACH_BURST_ONLY:-0}" \
  PAVONIS_RF_BLADE_STATE_DBG="${PAVONIS_RF_BLADE_STATE_DBG:-1}" \
  PAVONIS_RF_BLADE_STATE_DBG_MAX_LINES="${PAVONIS_RF_BLADE_STATE_DBG_MAX_LINES:-500}" \
  PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_FIRST="${PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_FIRST:-40}" \
  PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_EVERY="${PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_EVERY:-256}" \
  "$RUNNER" > "$OUT/runner.nohup.log" 2>&1 < /dev/null &
PID=$!

cat > "$OUT/launch.env" <<EOF2
PID=$PID
OUT=$OUT
RUNNER=$RUNNER
UE_STDOUT=$UE_STDOUT
UE_DETAIL=$UE_DETAIL
	PAVONIS_SRSUE_CELL_SELECT_TRACE=${PAVONIS_SRSUE_CELL_SELECT_TRACE:-0}
	PAVONIS_SRSUE_SIB1_TRACE=${PAVONIS_SRSUE_SIB1_TRACE:-0}
	PAVONIS_SRSUE_SIB1_TRACE_LIMIT=${PAVONIS_SRSUE_SIB1_TRACE_LIMIT:-400}
	PAVONIS_SRSUE_SIB1_TRACE_PDCCH_SUMMARY_INTERVAL=${PAVONIS_SRSUE_SIB1_TRACE_PDCCH_SUMMARY_INTERVAL:-200}
	PAVONIS_SRSUE_SI_CANDIDATE_TRACE=${PAVONIS_SRSUE_SI_CANDIDATE_TRACE:-0}
	PAVONIS_SRSUE_SI_CANDIDATE_TRACE_LIMIT=${PAVONIS_SRSUE_SI_CANDIDATE_TRACE_LIMIT:-200}
	PAVONIS_SRSUE_SI_CANDIDATE_TRACE_MIN_CORR=${PAVONIS_SRSUE_SI_CANDIDATE_TRACE_MIN_CORR:-0.40}
	PAVONIS_SRSUE_SI_CFO_PROVENANCE_TRACE=${PAVONIS_SRSUE_SI_CFO_PROVENANCE_TRACE:-0}
	PAVONIS_SRSUE_PRACH_CFG_DBG=${PAVONIS_SRSUE_PRACH_CFG_DBG:-1}
PAVONIS_SRSUE_RAR_TRACE=${PAVONIS_SRSUE_RAR_TRACE:-0}
PAVONIS_SRSUE_RAR_TRACE_LIMIT=${PAVONIS_SRSUE_RAR_TRACE_LIMIT:-240}
PAVONIS_SRSUE_RAR_CANDIDATE_TRACE=${PAVONIS_SRSUE_RAR_CANDIDATE_TRACE:-0}
PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_LIMIT=${PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_LIMIT:-200}
PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_MIN_CORR=${PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_MIN_CORR:-0.20}
PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE=${PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE:-0}
PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_LIMIT=${PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_LIMIT:-256}
PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_MIN_CORR=${PAVONIS_SRSUE_CRNTI_CANDIDATE_TRACE_MIN_CORR:-0.20}
PAVONIS_SRSUE_TA_HANDOFF_TRACE=${PAVONIS_SRSUE_TA_HANDOFF_TRACE:-0}
PAVONIS_SRSUE_TA_HANDOFF_APPLY_CURRENT=${PAVONIS_SRSUE_TA_HANDOFF_APPLY_CURRENT:-0}
PAVONIS_SRSUE_TA_HANDOFF_TRACE_LIMIT=${PAVONIS_SRSUE_TA_HANDOFF_TRACE_LIMIT:-64}
PAVONIS_SRSUE_TA_OFFSET_PRESERVE_COMMAND=${PAVONIS_SRSUE_TA_OFFSET_PRESERVE_COMMAND:-0}
PAVONIS_SRSUE_RAR_TRACE_LATE_ARM=${PAVONIS_SRSUE_RAR_TRACE_LATE_ARM:-1}
PAVONIS_SRSUE_RAR_WINDOW_TRACE=${PAVONIS_SRSUE_RAR_WINDOW_TRACE:-0}
SRSUE_PRACH_TX_DBG=${SRSUE_PRACH_TX_DBG:-1}
PAVONIS_RF_BLADE_TX_DBG=${PAVONIS_RF_BLADE_TX_DBG:-1}
PAVONIS_RF_BLADE_TX_DBG_FIRST=${PAVONIS_RF_BLADE_TX_DBG_FIRST:-16}
PAVONIS_RF_BLADE_TX_DBG_MAX_LINES=${PAVONIS_RF_BLADE_TX_DBG_MAX_LINES:-260}
PAVONIS_RF_BLADE_TX_DBG_MIN_PEAK=${PAVONIS_RF_BLADE_TX_DBG_MIN_PEAK:-0.20}
PAVONIS_RF_BLADE_TX_DBG_DUMP_COUNT=${PAVONIS_RF_BLADE_TX_DBG_DUMP_COUNT:-8}
PAVONIS_RF_BLADE_TX_DBG_DUMP_DIR=${PAVONIS_RF_BLADE_TX_DBG_DUMP_DIR:-$OUT}
PAVONIS_RF_BLADE_TX_DBG_PRE_TX=${PAVONIS_RF_BLADE_TX_DBG_PRE_TX:-1}
PAVONIS_RF_BLADE_TX_DBG_PRE_TX_ALL=${PAVONIS_RF_BLADE_TX_DBG_PRE_TX_ALL:-0}
PAVONIS_RF_BLADE_TX_DBG_TX_GUARD_SAMPLES=${PAVONIS_RF_BLADE_TX_DBG_TX_GUARD_SAMPLES:-30000}
PAVONIS_RF_BLADE_TX_DBG_PRACH_TIME_OFFSET_SAMPLES=${PAVONIS_RF_BLADE_TX_DBG_PRACH_TIME_OFFSET_SAMPLES:-0}
PAVONIS_RF_BLADE_TX_DBG_PRACH_FREQ_ROT_HZ=${PAVONIS_RF_BLADE_TX_DBG_PRACH_FREQ_ROT_HZ:-0}
PAVONIS_RF_BLADE_TX_DBG_HIGH_PEAK_TX_NOW=${PAVONIS_RF_BLADE_TX_DBG_HIGH_PEAK_TX_NOW:-0}
PAVONIS_RF_BLADE_TX_DBG_COHERENT_GUARD_BIAS=${PAVONIS_RF_BLADE_TX_DBG_COHERENT_GUARD_BIAS:-0}
PAVONIS_RF_BLADE_TX_DBG_RESTART_TX_STREAM_ON_FIRST_HIGH_PEAK=${PAVONIS_RF_BLADE_TX_DBG_RESTART_TX_STREAM_ON_FIRST_HIGH_PEAK:-0}
PAVONIS_RF_BLADE_TX_DBG_DISABLE_SOB_AFTER_ERROR=${PAVONIS_RF_BLADE_TX_DBG_DISABLE_SOB_AFTER_ERROR:-0}
PAVONIS_RF_BLADE_TX_DBG_SKIP_AFTER_ERROR=${PAVONIS_RF_BLADE_TX_DBG_SKIP_AFTER_ERROR:-0}
PAVONIS_SRSUE_PRACH_SYNC_GUARD_SLOTS=${PAVONIS_SRSUE_PRACH_SYNC_GUARD_SLOTS:-0}
PAVONIS_SRSUE_PRACH_SYNC_GUARD_TRACE=${PAVONIS_SRSUE_PRACH_SYNC_GUARD_TRACE:-0}
PAVONIS_SRSUE_PRACH_DEFER_MS=${PAVONIS_SRSUE_PRACH_DEFER_MS:-0}
PAVONIS_SRSUE_CAMPING_TTI_TRACE=${PAVONIS_SRSUE_CAMPING_TTI_TRACE:-0}
PAVONIS_SRSUE_CAMPING_TTI_ALIGN=${PAVONIS_SRSUE_CAMPING_TTI_ALIGN:-0}
PAVONIS_SRSUE_UL_TX_LATTICE=${PAVONIS_SRSUE_UL_TX_LATTICE:-0}
PAVONIS_SRSUE_UL_TX_LATTICE_MAX_SLEW_SAMPLES=${PAVONIS_SRSUE_UL_TX_LATTICE_MAX_SLEW_SAMPLES:-1}
PAVONIS_SRSUE_SFN_ACQ_HANDOFF=${PAVONIS_SRSUE_SFN_ACQ_HANDOFF:-0}
PAVONIS_SRSUE_SFN_ACQ_TARGET_OFFSET_SAMPLES=${PAVONIS_SRSUE_SFN_ACQ_TARGET_OFFSET_SAMPLES:-2048}
PAVONIS_SRSUE_SR_PUCCH_TRACE=${PAVONIS_SRSUE_SR_PUCCH_TRACE:-0}
PAVONIS_SRSUE_SR_PUCCH_TRACE_LIMIT=${PAVONIS_SRSUE_SR_PUCCH_TRACE_LIMIT:-256}
PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_SOB=${PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_SOB:-0}
PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_EOB=${PAVONIS_RF_BLADE_FORCE_HIGH_PEAK_EOB:-0}
PAVONIS_RF_BLADE_HIGH_PEAK_EOB_THEN_SOB=${PAVONIS_RF_BLADE_HIGH_PEAK_EOB_THEN_SOB:-0}
PAVONIS_RF_BLADE_PRACH_BURST_ONLY=${PAVONIS_RF_BLADE_PRACH_BURST_ONLY:-0}
PAVONIS_RF_BLADE_STATE_DBG=${PAVONIS_RF_BLADE_STATE_DBG:-1}
PAVONIS_RF_BLADE_STATE_DBG_MAX_LINES=${PAVONIS_RF_BLADE_STATE_DBG_MAX_LINES:-500}
PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_FIRST=${PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_FIRST:-40}
PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_EVERY=${PAVONIS_RF_BLADE_STATE_DBG_GET_TIME_EVERY:-256}
UE_TX_GAIN_DB_OVERRIDE=${UE_TX_GAIN_DB:-}
EOF2

echo "TAG=$TAG"
echo "STAMP=$STAMP"
echo "PID=$PID"
echo "OUT=$OUT"
echo "UE_STDOUT=$UE_STDOUT"
echo "RESULT_ENV=$OUT/result.env"
