#!/usr/bin/env bash
set -euo pipefail

ART="${ART:-@CONTROLLER_HARNESS@}"
STAMP="${STAMP:-$(date -u +%Y%m%dT%H%M%SZ)CP2188_COHERENT_20MS_UL_RETIME_LADDER}"
TAG="${TAG:-codex_stage6_cp2188_coherent_20ms_ul_retime_ladder}"

export ART STAMP TAG
export PAVONIS_PHYSICAL_PATH_CLEARED=1
export PAVONIS_ALLOW_RF_TX=1
export GNB_DURATION=420
export TX_BACKOFF="${TX_BACKOFF:-10}"
export TX_ATT="${TX_ATT:-5}"
export GNB_RX_GAIN=40
export TX_TIME_OFFSET_NS="${TX_TIME_OFFSET_NS:-20000000}"
export TX_WRITE_TIMEOUT_US=1000

export PAVONIS_GNB_SI_PDSCH_POWER_SIGN_COMPAT=1
export GNB_POWER_CONTROL_OFFSET_SS_DB=6
export PAVONIS_NON_PRACH_UL_RX_TIMESTAMP_OFFSET_SAMPLES="${PAVONIS_NON_PRACH_UL_RX_TIMESTAMP_OFFSET_SAMPLES:--237336}"
export PAVONIS_PRACH_TIMING_COMPENSATION_REPORT_SLOT_OFFSET=0
export PAVONIS_GNB_RA_RESP_WINDOW=40
export PAVONIS_ALLOW_EXTENDED_RA_RESP_WINDOW="${PAVONIS_ALLOW_EXTENDED_RA_RESP_WINDOW:-1}"

export M2SDR_SOAPY_TX_FULL_RING_REFRESH_US=50
export M2SDR_SOAPY_TX_WORKER_PKT_COUNT=64
export PAVONIS_SOAPY_TX_TIMEOUT_RETRY_OVERRIDE=0
export PAVONIS_SOAPY_TX_TIMEOUT_RETRY_MAX_OVERRIDE=0
export PAVONIS_SOAPY_TX_TIMEOUT_RETRY_US_OVERRIDE=1000
export PAVONIS_SOAPY_TX_DEADLINE_WRITE_OVERRIDE="${PAVONIS_SOAPY_TX_DEADLINE_WRITE_OVERRIDE:-1}"
export PAVONIS_SOAPY_TX_DEADLINE_WRITE_GUARD_US_OVERRIDE=2000
export PAVONIS_SOAPY_TX_DEADLINE_WRITE_MAX_TIMEOUT_US_OVERRIDE=50000

export PAVONIS_PRACH_DEMOD_INPUT_STAGE1_POLICY=1
export PAVONIS_PRACH_DEMOD_INPUT_STAGE1_CANDIDATE_LIST="${PAVONIS_PRACH_DEMOD_INPUT_STAGE1_CANDIDATE_LIST_OVERRIDE:--192:-0.5:20000,-192:-0.5:35000,-192:-0.5:45000,64:-0.5:5000,64:-0.5:10000,64:-0.5:15000,64:-0.5:20000}"
export PAVONIS_PRACH_DEMOD_INPUT_STAGE1_MAX_CANDIDATES="${PAVONIS_PRACH_DEMOD_INPUT_STAGE1_MAX_CANDIDATES_OVERRIDE:-8}"
export PAVONIS_PRACH_DEMOD_INPUT_STAGE1_STOP_ON_ACCEPT=1
export PAVONIS_PRACH_STAGE1_TA_COMPENSATE_SELECTED_SHIFT="${PAVONIS_PRACH_STAGE1_TA_COMPENSATE_SELECTED_SHIFT:-1}"
export PAVONIS_PRACH_DEMOD_INPUT_STAGE1_TRACE=1
export PAVONIS_PRACH_DEMOD_INPUT_STAGE1_TRACE_MAX=8192
export PAVONIS_PRACH_STRONG_PREDEMOD_CAPTURE=1
export PAVONIS_PRACH_STRONG_PREDEMOD_RAW_MAX=16
export PAVONIS_PRACH_STRONG_PREDEMOD_RMS_DB_FLOOR=-65
export PAVONIS_PRACH_STRONG_PREDEMOD_PEAK_DB_FLOOR=-55
export PAVONIS_PRACH_STRONG_PREDEMOD_ARM_FILE="/tmp/pavonis_prach_stage6_cp1733_currentbinary_cp1658cadence_${STAMP}_arm"
export PRACH_COLLECTION_EXTRA_SAMPLES="${PRACH_COLLECTION_EXTRA_SAMPLES_OVERRIDE:-12000}"
export GNB_PRACH_TIMING_COMPENSATION_SAMPLES="${GNB_PRACH_TIMING_COMPENSATION_SAMPLES_OVERRIDE:-237336}"

export PAVONIS_SRSUE_RAR_TRACE=1
export PAVONIS_SRSUE_RAR_TRACE_LIMIT=1200
export PAVONIS_SRSUE_RAR_TRACE_LATE_ARM=1
export PAVONIS_SRSUE_RAR_WINDOW_TRACE=1
export PAVONIS_SRSUE_RAR_CANDIDATE_TRACE=1
export PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_LIMIT=1200
export PAVONIS_SRSUE_RAR_CANDIDATE_TRACE_MIN_CORR=0.00
export PAVONIS_SRSUE_RAR_PATH_TRACE=1
export PAVONIS_SRSUE_RAR_PATH_TRACE_LIMIT=1200

export PAVONIS_GNB_RAR_PDU_TRACE=1
export PAVONIS_GNB_RAR_SCHED_TRACE=1
export PAVONIS_GNB_RAR_SCHED_TRACE_LIMIT=256
export PAVONIS_GNB_RAR_FAPI_TRACE=1
export PAVONIS_GNB_RAR_FAPI_TRACE_PATH=/tmp/pavonis_gnb_rar_fapi_trace.tsv
export PAVONIS_GNB_RAR_FAPI_TRACE_LIMIT=256
export PAVONIS_GNB_RAR_TX_WORKER_TRACE_ARM="${PAVONIS_GNB_RAR_TX_WORKER_TRACE_ARM_OVERRIDE:-1}"
export M2SDR_SOAPY_TX_WORKER_TRACE_PATH="${M2SDR_SOAPY_TX_WORKER_TRACE_PATH_OVERRIDE:-/tmp/pavonis_m2sdr_tx_worker_trace.tsv}"
export M2SDR_SOAPY_TX_WORKER_TRACE_ARM_FILE="${M2SDR_SOAPY_TX_WORKER_TRACE_ARM_FILE_OVERRIDE-/tmp/pavonis_cp2188_rar_tx_worker_${STAMP}.arm}"
export M2SDR_SOAPY_TX_WORKER_TRACE_LIMIT="${M2SDR_SOAPY_TX_WORKER_TRACE_LIMIT:-65536}"
export M2SDR_SOAPY_TX_WORKER_TRACE_FLUSH_PERIOD=256

export PAVONIS_SOAPY_RX_APPEND_ENABLE="${PAVONIS_SOAPY_RX_APPEND_ENABLE:-0}"
export PAVONIS_UL_SYMBOL_DUMP=1
export PAVONIS_UL_SYMBOL_METADATA_ONLY="${PAVONIS_UL_SYMBOL_METADATA_ONLY_OVERRIDE:-1}"
export PAVONIS_UL_SYMBOL_RAW_MAX="${PAVONIS_UL_SYMBOL_RAW_MAX_OVERRIDE:-0}"

exec bash "$ART/cp1807_run_stage6_raresp40_realue_rar_msg3.sh"
