#!/usr/bin/env bash
set -euo pipefail

ART="${ART:-@CONTROLLER_HARNESS@}"
STAMP="${STAMP:-$(date -u +%Y%m%dT%H%M%SZ)CP2192_PUSCH_CSI_LADDER}"
TAG="${TAG:-codex_stage6_cp2192_pusch_csi_ladder}"

export ART STAMP TAG
export PAVONIS_PUXCH_ORDER_TRACE="${PAVONIS_PUXCH_ORDER_TRACE:-0}"
export PAVONIS_PUXCH_ORDER_TRACE_LATE_ARM="${PAVONIS_PUXCH_ORDER_TRACE_LATE_ARM:-0}"
export PAVONIS_PUSCH_CSI_TRACE=1
export PAVONIS_PUSCH_CSI_TRACE_LIMIT=128
export PAVONIS_GNB_INPROCESS_UL_SYMBOL_ARM="${PAVONIS_GNB_INPROCESS_UL_SYMBOL_ARM_OVERRIDE:-1}"
export PAVONIS_GNB_INPROCESS_UL_SYMBOL_ARM_EVENT=rar_pdu
export PAVONIS_UL_SYMBOL_DUMP_ARM_MODE="${PAVONIS_UL_SYMBOL_DUMP_ARM_MODE_OVERRIDE:-after_rar}"

exec bash "$ART/cp2188_run_coherent_20ms_ul_retime_ladder.sh"
