#!/usr/bin/env bash
set -euo pipefail

ART="${ART:-@CONTROLLER_HARNESS@}"
STAMP="${STAMP:-$(date -u +%Y%m%dT%H%M%SZ)CP2209_SI_SUPPLY_DISCRIMINATOR}"
TAG="${TAG:-codex_stage6_cp2209_si_supply_discriminator}"

export ART STAMP TAG

export PAVONIS_GNB_SI_OCCASION_TRACE=1
export PAVONIS_GNB_SI_OCCASION_TRACE_LIMIT=4096
export M2SDR_SOAPY_TX_WORKER_TRACE_ARM_FILE_OVERRIDE="${M2SDR_SOAPY_TX_WORKER_TRACE_ARM_FILE_OVERRIDE-}"

export PAVONIS_SRSUE_SI_CANDIDATE_TRACE=1
export PAVONIS_SRSUE_SI_CANDIDATE_TRACE_LIMIT=1200
export PAVONIS_SRSUE_SI_CANDIDATE_TRACE_MIN_CORR=0.20
export PAVONIS_SRSUE_SI_CFO_PROVENANCE_TRACE=1

exec bash "$ART/cp2206_run_measured_msg3_offset.sh"
