#!/usr/bin/env bash
set -euo pipefail

ART="${ART:-@CONTROLLER_HARNESS@}"
STAMP="${STAMP:-$(date -u +%Y%m%dT%H%M%SZ)CP2212_DYNAMIC_NONPRACH_OFFSET}"
TAG="${TAG:-codex_stage6_cp2212_dynamic_nonprach_offset}"

export ART STAMP TAG
export PAVONIS_NON_PRACH_UL_RX_TIMESTAMP_OFFSET_SAMPLES="${PAVONIS_NON_PRACH_UL_RX_TIMESTAMP_OFFSET_SAMPLES:--241118}"
export PAVONIS_NON_PRACH_UL_RX_OFFSET_FROM_STAGE1="${PAVONIS_NON_PRACH_UL_RX_OFFSET_FROM_STAGE1:-1}"
export PAVONIS_NON_PRACH_UL_RX_OFFSET_NEGATIVE_SHIFT_SAMPLES="${PAVONIS_NON_PRACH_UL_RX_OFFSET_NEGATIVE_SHIFT_SAMPLES:--241118}"
export PAVONIS_NON_PRACH_UL_RX_OFFSET_POSITIVE_SHIFT_SAMPLES="${PAVONIS_NON_PRACH_UL_RX_OFFSET_POSITIVE_SHIFT_SAMPLES:--237798}"
export PAVONIS_NON_PRACH_UL_RX_OFFSET_TRACE_LIMIT="${PAVONIS_NON_PRACH_UL_RX_OFFSET_TRACE_LIMIT:-64}"

exec bash "$ART/cp2209_run_si_supply_discriminator.sh"
