#!/usr/bin/env bash
set -euo pipefail

ART="${ART:-@CONTROLLER_HARNESS@}"
STAMP="${STAMP:-$(date -u +%Y%m%dT%H%M%SZ)CP2201_SCHEDULED_MSG3_TARGET_CAPTURE}"
TAG="${TAG:-codex_stage6_cp2201_scheduled_msg3_target_capture}"

export ART STAMP TAG
export PAVONIS_PUSCH_EVM_DIAGNOSTIC=1
export PAVONIS_GNB_RAR_TX_WORKER_TRACE_ARM_OVERRIDE="${PAVONIS_GNB_RAR_TX_WORKER_TRACE_ARM_OVERRIDE:-0}"
export PAVONIS_UL_SYMBOL_METADATA_ONLY_OVERRIDE=1
export PAVONIS_UL_SYMBOL_RAW_MAX_OVERRIDE=128
export PAVONIS_UL_SYMBOL_RAW_PEAK_MIN=1e9
export PAVONIS_UL_SYMBOL_RAW_RMS_MIN=1e9
export PAVONIS_UL_SYMBOL_DUMP_ARM_MODE_OVERRIDE=scheduled_msg3
export PAVONIS_GNB_INPROCESS_UL_SYMBOL_ARM_OVERRIDE=0
export PAVONIS_UL_SYMBOL_MSG3_TARGET_CAPTURE=1
export PAVONIS_UL_SYMBOL_MSG3_TARGET_MAX=8

exec bash "$ART/cp2192_run_pusch_csi_ladder.sh"
