#!/usr/bin/env bash
set -euo pipefail

ART="${ART:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
STAMP="${STAMP:-$(date -u +%Y%m%dT%H%M%SZ)CP2313_PUCCH_F1_PHASE_SEARCH_FULL_BANK}"
TAG="${TAG:-codex_stage6_cp2313_pucch_f1_phase_search_full_bank}"

export ART STAMP TAG
export PAVONIS_SRSUE_SR_PUCCH_TRACE=1
export PAVONIS_SRSUE_SR_PUCCH_TRACE_LIMIT=512
export PAVONIS_PUCCH_RESULT_TRACE=1
export PAVONIS_PUCCH_RESULT_TRACE_LIMIT=512
export PAVONIS_PUCCH_F1_GRID_CAPTURE=1
export PAVONIS_PUCCH_F1_GRID_CAPTURE_MAX=4
export PAVONIS_PUCCH_F1_GRID_CAPTURE_MIN_EPRE_DB=-60
export PAVONIS_PUCCH_F1_SYMBOL_PHASE_STEP_DEG=12.2
export PAVONIS_PUCCH_F1_SUBCARRIER_PHASE_STEP_DEG=-72.0
export PAVONIS_PUCCH_F1_PHASE_SEARCH_CANDIDATES='4:-178,8:90,8:-96,6:-104,4:-112,2:-120,0:-128'
export PAVONIS_PUCCH_F1_PHASE_SEARCH_TRACE_LIMIT=128

exec bash "$ART/cp2302_run_pucch_grid_candidate_supply.sh"
