#!/usr/bin/env bash
set -euo pipefail

VALIDATION_ROOT=@REMOTE_HOME@/CLionProjects/m2sdr/litex_m2sdr/software/validation/ocudu
SCRIPT_DIR="$VALIDATION_ROOT/scripts"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/env_ocudu_validation.sh"
export PAVONIS_SOAPY_TX_FORCE_ATT_DB=16

ACK=0
START_UE=0
UE_CONF=''
GNB_CONF=''
SIM_FILE=''
EXTERNAL_IFACE="${OCUDU_VALIDATION_EXTERNAL_IFACE:-@RAN_INTERFACE@}"
DURATION="${OCUDU_VALIDATION_OTA_DURATION:-420}"

usage() {
  echo 'usage: gnb-only-stage --i-understand-rf-test --gnb-conf FILE --sim-file FILE --ue-conf FILE [--duration SEC] [--external-iface IFACE]' >&2
}

while (($#)); do
  case "$1" in
    --i-understand-rf-test) ACK=1; shift ;;
    --start-ue) START_UE=1; shift ;;
    --ue-conf) UE_CONF="${2:?missing path}"; shift 2 ;;
    --gnb-conf) GNB_CONF="${2:?missing path}"; shift 2 ;;
    --sim-file) SIM_FILE="${2:?missing path}"; shift 2 ;;
    --duration) DURATION="${2:?missing seconds}"; shift 2 ;;
    --external-iface) EXTERNAL_IFACE="${2:?missing interface}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) usage; exit 2 ;;
  esac
done

((ACK == 1)) || { echo 'RF acknowledgement missing' >&2; exit 2; }
((START_UE == 0)) || { echo 'This stage never owns a UE' >&2; exit 2; }
[[ "$DURATION" =~ ^[0-9]+$ ]] && ((DURATION > 0 && DURATION <= 600)) || {
  echo 'Duration must be 1..600 seconds' >&2
  exit 2
}
[[ -f "$UE_CONF" && -f "$SIM_FILE" && -f "$GNB_CONF" ]]
[[ -x "$OCUDU_GNB_BIN" ]]
[[ -n "$EXTERNAL_IFACE" ]]

RUN_DIR="$VALIDATION_RUN_ROOT/$(date -u +%Y%m%d_%H%M%S)_ota-stage"
mkdir -p "$RUN_DIR"
touch "$RUN_DIR"/{qcore.log,srsue.log,setup.log,pids.txt}
cp "$GNB_CONF" "$RUN_DIR/gnb-run.yml"

# The continuous wrapper owns qcore on the host LAN address. Only retarget N2;
# all RF, cell, and N3 defaults remain those generated by the coherent fixture.
python3 - "$RUN_DIR/gnb-run.yml" <<'PY'
from pathlib import Path
import sys
import yaml

path = Path(sys.argv[1])
doc = yaml.safe_load(path.read_text())
amf = doc["cu_cp"]["amf"]
assert amf["addr"] == "127.0.0.1"
assert amf["bind_addr"] == "127.0.0.2"
amf["addr"] = "@CORE_N2_IP@"
amf["bind_addr"] = "@CORE_N2_IP@"
path.write_text(yaml.safe_dump(doc, sort_keys=False))
PY

{
  printf 'gNB source config sha256: %s\n' "$(sha256sum "$GNB_CONF" | awk '{print $1}')"
  printf 'gNB run config sha256: %s\n' "$(sha256sum "$RUN_DIR/gnb-run.yml" | awk '{print $1}')"
  printf 'UE config sha256: %s\n' "$(sha256sum "$UE_CONF" | awk '{print $1}')"
  printf 'qcore SIM file sha256: %s\n' "$(sha256sum "$SIM_FILE" | awk '{print $1}')"
  printf 'external qcore endpoint: @CORE_N2_IP@:38412\n'
} >"$RUN_DIR/commands-and-checksums.txt"

cleanup() {
  set +e
  if [[ "${GNB_PID:-}" =~ ^[0-9]+$ ]] && kill -0 "$GNB_PID" 2>/dev/null; then
    kill -TERM -- "-$GNB_PID" 2>/dev/null || kill -TERM "$GNB_PID" 2>/dev/null || true
    for _ in $(seq 1 50); do
      kill -0 "$GNB_PID" 2>/dev/null || break
      sleep 0.1
    done
    kill -0 "$GNB_PID" 2>/dev/null && kill -KILL -- "-$GNB_PID" 2>/dev/null || true
  fi
  if [[ -e /sys/module/m2sdr/parameters/dma_reader_program_mode ]]; then
    echo N | sudo -n tee /sys/module/m2sdr/parameters/dma_reader_program_mode >/dev/null || true
  fi
  if [[ ! -f "$RUN_DIR/RESULT.md" ]]; then
    printf '# gNB-only OTA stage\n\nResult: interrupted or failed\n' >"$RUN_DIR/RESULT.md"
  fi
}
trap cleanup EXIT INT TERM HUP

echo "stage $$" >>"$RUN_DIR/pids.txt"
pgrep -x qcore >/dev/null
sudo -n ss -A sctp -ln | grep -q '@CORE_N2_IP@:38412'
"$SCRIPT_DIR/check_m2sdr_clock_gate.sh" "$RUN_DIR/clk-test.log" >"$RUN_DIR/clock-gate.log"
"$SCRIPT_DIR/collect_host_state.sh" "$RUN_DIR" >"$RUN_DIR/collect-host-state.log" 2>&1

setsid "$OCUDU_GNB_BIN" -c "$RUN_DIR/gnb-run.yml" < /dev/null >"$RUN_DIR/gnb.log" 2>&1 &
GNB_PID=$!
echo "gnb $GNB_PID" >>"$RUN_DIR/pids.txt"

ready=0
for _ in $(seq 1 200); do
  if grep -q 'N2: Connection to AMF on @CORE_N2_IP@:38412 completed' "$RUN_DIR/gnb.log"; then
    ready=1
    break
  fi
  kill -0 "$GNB_PID" 2>/dev/null || break
  sleep 0.1
done
[[ "$ready" == 1 ]] || {
  tail -n 80 "$RUN_DIR/gnb.log"
  exit 1
}

sleep "$DURATION"
cat >"$RUN_DIR/RESULT.md" <<EOF
# gNB-only OTA stage

Date: $(date --iso-8601=seconds)
Host: $(hostname)
Run directory: $RUN_DIR
Bounded duration: $DURATION seconds
External qcore preserved: yes
Highest attempted stage: Android phone OTA through coherent M2SDR
EOF
echo "Bounded gNB-only OTA stage complete: $RUN_DIR"
